spring:
  application:
    name: eureka-server

eureka:
  renewalPercentThreshold: 2
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client.register-with-eureka: true
  client.fetch-registry: true
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level.com.netflix.eureka: OFF
  level.com.netflix.discovery: OFF

error:
  whitelabel:
    enabled: false
server:
  port: 8761