spring:
  application:
    name: eureka-server
  data:
    mongodb:
      host: localhost
      port: 27017
      database: eureka-server

eureka:
  renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
  client.register-with-eureka: false
  client.fetch-registry: false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level.com.netflix.eureka: OFF
  level.com.netflix.discovery: OFF

error:
  whitelabel:
    enabled: false
server:
  port: 8761